-- Barbería Pergamino · esquema D1 (el Worker también lo crea solo la primera vez que se usa).
CREATE TABLE IF NOT EXISTS bp_settings (k TEXT PRIMARY KEY,v TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS bp_staff (id TEXT PRIMARY KEY,name TEXT NOT NULL,role TEXT NOT NULL,pin_hash TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS bp_services (id TEXT PRIMARY KEY,name TEXT NOT NULL,price INTEGER NOT NULL,duration INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS bp_clients (id TEXT PRIMARY KEY,name TEXT NOT NULL,whatsapp TEXT UNIQUE NOT NULL,birthday TEXT,visits INTEGER NOT NULL DEFAULT 0,no_shows INTEGER NOT NULL DEFAULT 0,total_spent INTEGER NOT NULL DEFAULT 0,last_visit TEXT);
CREATE TABLE IF NOT EXISTS bp_appts (id TEXT PRIMARY KEY,client_id TEXT NOT NULL,staff_id TEXT NOT NULL,service_id TEXT NOT NULL,service_name TEXT NOT NULL,price INTEGER NOT NULL,duration INTEGER NOT NULL,date TEXT NOT NULL,time TEXT NOT NULL DEFAULT '',kind TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',pay TEXT,amount INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS bp_expenses (id TEXT PRIMARY KEY,date TEXT NOT NULL,concept TEXT NOT NULL,amount INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS bp_payouts (id TEXT PRIMARY KEY,staff_id TEXT NOT NULL,date TEXT NOT NULL,amount INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS bp_promos (id TEXT PRIMARY KEY,title TEXT NOT NULL,pct INTEGER NOT NULL,service_id TEXT,start TEXT NOT NULL,end TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,kind TEXT NOT NULL DEFAULT 'pct',message TEXT);
CREATE TABLE IF NOT EXISTS bp_subs (id TEXT PRIMARY KEY,role TEXT NOT NULL,ref TEXT NOT NULL,endpoint TEXT NOT NULL,p256dh TEXT NOT NULL,auth TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(endpoint,role,ref));
CREATE INDEX IF NOT EXISTS bp_subs_r ON bp_subs(role,ref);
CREATE TABLE IF NOT EXISTS bp_notif (id TEXT PRIMARY KEY,staff_id TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'turno',body TEXT NOT NULL,seen INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,pushed INTEGER NOT NULL DEFAULT 0,title TEXT);
CREATE INDEX IF NOT EXISTS bp_notif_s ON bp_notif(staff_id,seen);
CREATE TABLE IF NOT EXISTS bp_sessions (token TEXT PRIMARY KEY,staff_id TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
