-- Esquema completo de la base D1 (generado desde el Worker; incluye todas las tablas y columnas actuales).
-- El Worker también lo crea y actualiza solo al arrancar (función init), y carga los datos iniciales.
-- Si cambiás el esquema en worker.js, volvé a generar este archivo para que no quede desactualizado.

CREATE TABLE IF NOT EXISTS bp_appts (id TEXT PRIMARY KEY,client_id TEXT NOT NULL,staff_id TEXT NOT NULL,service_id TEXT NOT NULL,service_name TEXT NOT NULL,price INTEGER NOT NULL,duration INTEGER NOT NULL,date TEXT NOT NULL,time TEXT NOT NULL DEFAULT '',kind TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',pay TEXT,amount INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, reminded INTEGER NOT NULL DEFAULT 0, extras TEXT, prod_total INTEGER NOT NULL DEFAULT 0, prod_comm INTEGER NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS bp_audit (id TEXT PRIMARY KEY,at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,staff_id TEXT,staff_name TEXT,action TEXT NOT NULL,detail TEXT);

CREATE TABLE IF NOT EXISTS bp_blocks (id TEXT PRIMARY KEY,staff_id TEXT,d1 TEXT NOT NULL,d2 TEXT NOT NULL,t1 TEXT,t2 TEXT,note TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS bp_cash (date TEXT PRIMARY KEY,expected INTEGER NOT NULL,counted INTEGER NOT NULL,diff INTEGER NOT NULL,staff_id TEXT,staff_name TEXT,at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS bp_clients (id TEXT PRIMARY KEY,name TEXT NOT NULL,whatsapp TEXT UNIQUE NOT NULL,birthday TEXT,visits INTEGER NOT NULL DEFAULT 0,no_shows INTEGER NOT NULL DEFAULT 0,total_spent INTEGER NOT NULL DEFAULT 0,last_visit TEXT, notes TEXT);

CREATE TABLE IF NOT EXISTS bp_expenses (id TEXT PRIMARY KEY,date TEXT NOT NULL,concept TEXT NOT NULL,amount INTEGER NOT NULL, category TEXT, pay TEXT);

CREATE TABLE IF NOT EXISTS bp_fees (id TEXT PRIMARY KEY,client_id TEXT NOT NULL,appt_id TEXT,amount INTEGER NOT NULL,date TEXT NOT NULL,paid INTEGER NOT NULL DEFAULT 0,paid_date TEXT, pay TEXT);

CREATE TABLE IF NOT EXISTS bp_images (id TEXT PRIMARY KEY,mime TEXT NOT NULL,data TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS bp_items (id TEXT PRIMARY KEY,appt_id TEXT NOT NULL,product_id TEXT NOT NULL,name TEXT NOT NULL,qty INTEGER NOT NULL,price INTEGER NOT NULL,comm_pct INTEGER NOT NULL DEFAULT 0,held INTEGER NOT NULL DEFAULT 0, cost INTEGER NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS bp_limits (k TEXT PRIMARY KEY,n INTEGER NOT NULL DEFAULT 0,t INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS bp_notif (id TEXT PRIMARY KEY,staff_id TEXT NOT NULL,kind TEXT NOT NULL DEFAULT 'turno',body TEXT NOT NULL,seen INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,pushed INTEGER NOT NULL DEFAULT 0,title TEXT);

CREATE TABLE IF NOT EXISTS bp_payouts (id TEXT PRIMARY KEY,staff_id TEXT NOT NULL,date TEXT NOT NULL,amount INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS bp_products (id TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT,price INTEGER NOT NULL,stock INTEGER NOT NULL DEFAULT 0,track INTEGER NOT NULL DEFAULT 1,low INTEGER NOT NULL DEFAULT 3,comm_pct INTEGER NOT NULL DEFAULT 0,photo TEXT,active INTEGER NOT NULL DEFAULT 1, cost INTEGER NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS bp_promos (id TEXT PRIMARY KEY,title TEXT NOT NULL,pct INTEGER NOT NULL,service_id TEXT,start TEXT NOT NULL,end TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,kind TEXT NOT NULL DEFAULT 'pct', message TEXT);

CREATE TABLE IF NOT EXISTS bp_recurring (id TEXT PRIMARY KEY,concept TEXT NOT NULL,category TEXT,amount INTEGER NOT NULL,day INTEGER NOT NULL,pay TEXT,active INTEGER NOT NULL DEFAULT 1,last_month TEXT);

CREATE TABLE IF NOT EXISTS bp_services (id TEXT PRIMARY KEY,name TEXT NOT NULL,price INTEGER NOT NULL,duration INTEGER NOT NULL, description TEXT, photo TEXT, online INTEGER NOT NULL DEFAULT 1, addon INTEGER NOT NULL DEFAULT 0, addon_to TEXT);

CREATE TABLE IF NOT EXISTS bp_sessions (token TEXT PRIMARY KEY,staff_id TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS bp_settings (k TEXT PRIMARY KEY,v TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS bp_staff (id TEXT PRIMARY KEY,name TEXT NOT NULL,role TEXT NOT NULL,pin_hash TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1, comm INTEGER);

CREATE TABLE IF NOT EXISTS bp_subs (id TEXT PRIMARY KEY,role TEXT NOT NULL,ref TEXT NOT NULL,endpoint TEXT NOT NULL,p256dh TEXT NOT NULL,auth TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(endpoint,role,ref));

CREATE INDEX IF NOT EXISTS bp_items_a ON bp_items(appt_id);

CREATE INDEX IF NOT EXISTS bp_notif_s ON bp_notif(staff_id,seen);

CREATE INDEX IF NOT EXISTS bp_subs_r ON bp_subs(role,ref);
